ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_blob_digest_not_null" TO "content_blob_refs_blob_digest_not_null";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_created_at_not_null" TO "content_blob_refs_created_at_not_null";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_id_not_null" TO "content_blob_refs_id_not_null";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_manifest_id_not_null" TO "content_blob_refs_manifest_id_not_null";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_manifest_id_oci_manifests_id_fk" TO "content_blob_refs_manifest_id_content_manifests_id_fk";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_package_id_not_null" TO "content_blob_refs_package_id_not_null";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_package_id_packages_id_fk" TO "content_blob_refs_package_id_packages_id_fk";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_pkey" TO "content_blob_refs_pkey";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_repository_id_not_null" TO "content_blob_refs_repository_id_not_null";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_repository_id_repositories_id_fk" TO "content_blob_refs_repository_id_repositories_id_fk";--> statement-breakpoint
ALTER TABLE "content_blob_refs" RENAME CONSTRAINT "oci_manifest_blob_refs_updated_at_not_null" TO "content_blob_refs_updated_at_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_created_at_not_null" TO "content_manifests_created_at_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_digest_not_null" TO "content_manifests_digest_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_id_not_null" TO "content_manifests_id_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_media_type_not_null" TO "content_manifests_media_type_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_pkey" TO "content_manifests_pkey";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_raw_not_null" TO "content_manifests_raw_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_repository_id_not_null" TO "content_manifests_repository_id_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_repository_id_repositories_id_fk" TO "content_manifests_repository_id_repositories_id_fk";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_size_bytes_not_null" TO "content_manifests_size_bytes_not_null";--> statement-breakpoint
ALTER TABLE "content_manifests" RENAME CONSTRAINT "oci_manifests_updated_at_not_null" TO "content_manifests_updated_at_not_null";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_created_at_not_null" TO "content_tags_created_at_not_null";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_id_not_null" TO "content_tags_id_not_null";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_manifest_id_not_null" TO "content_tags_manifest_id_not_null";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_manifest_id_oci_manifests_id_fk" TO "content_tags_manifest_id_content_manifests_id_fk";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_package_id_not_null" TO "content_tags_package_id_not_null";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_package_id_packages_id_fk" TO "content_tags_package_id_packages_id_fk";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_pkey" TO "content_tags_pkey";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_repository_id_not_null" TO "content_tags_repository_id_not_null";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_repository_id_repositories_id_fk" TO "content_tags_repository_id_repositories_id_fk";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_tag_not_null" TO "content_tags_tag_not_null";--> statement-breakpoint
ALTER TABLE "content_tags" RENAME CONSTRAINT "oci_tags_updated_at_not_null" TO "content_tags_updated_at_not_null";
