import { describe, expect, test } from "bun:test";
import {
  ArchPkgFileSchema,
  ArchPkgNameSchema,
  ArchPkgVerSchema,
  archPkgFileName,
  isArchPkgFile,
  isValidArchArch,
  parseArchPkgFileName,
  parsePkgInfo,
} from "./arch-validation";

describe("arch validation", () => {
  test("pkgname/pkgver/arch schemas accept valid tokens", () => {
    expect(ArchPkgNameSchema.safeParse("foo-bar").success).toBe(true);
    expect(ArchPkgNameSchema.safeParse("python-attrs@2").success).toBe(true);
    expect(ArchPkgNameSchema.safeParse("-bad").success).toBe(false);
    expect(ArchPkgVerSchema.safeParse("1.2.3-1").success).toBe(true);
    expect(ArchPkgVerSchema.safeParse("2:1.0-3").success).toBe(true);
    expect(ArchPkgVerSchema.safeParse("bad ver").success).toBe(false);
    expect(isValidArchArch("x86_64")).toBe(true);
    expect(isValidArchArch("any")).toBe(true);
    expect(isValidArchArch("bad/arch")).toBe(false);
  });

  test("package filename schema only accepts .pkg.tar.zst/.xz without separators", () => {
    expect(ArchPkgFileSchema.safeParse("foo-1.2.3-1-x86_64.pkg.tar.zst").success).toBe(true);
    expect(ArchPkgFileSchema.safeParse("foo-1.2.3-1-x86_64.pkg.tar.xz").success).toBe(true);
    expect(ArchPkgFileSchema.safeParse("foo-1.2.3-1-x86_64.pkg.tar.gz").success).toBe(false);
    expect(ArchPkgFileSchema.safeParse("a/b.pkg.tar.zst").success).toBe(false);
    expect(isArchPkgFile("foo-1.2.3-1-x86_64.pkg.tar.zst")).toBe(true);
    expect(isArchPkgFile("foo.db")).toBe(false);
  });

  test("parseArchPkgFileName splits name/ver/arch from the right", () => {
    expect(parseArchPkgFileName("foo-1.2.3-1-x86_64.pkg.tar.zst")).toEqual({
      pkgname: "foo",
      pkgver: "1.2.3-1",
      arch: "x86_64",
    });
    // A hyphenated package name is preserved (only the trailing ver-rel-arch split).
    expect(parseArchPkgFileName("my-cool-pkg-2.0-3-aarch64.pkg.tar.xz")).toEqual({
      pkgname: "my-cool-pkg",
      pkgver: "2.0-3",
      arch: "aarch64",
    });
    expect(parseArchPkgFileName("notapackage.txt")).toBeNull();
    expect(parseArchPkgFileName("foo.pkg.tar.zst")).toBeNull();
  });

  test("archPkgFileName round-trips with parseArchPkgFileName", () => {
    const file = archPkgFileName({ pkgname: "foo", pkgver: "1.2.3-1", arch: "x86_64" });
    expect(file).toBe("foo-1.2.3-1-x86_64.pkg.tar.zst");
    expect(parseArchPkgFileName(file)).toEqual({
      pkgname: "foo",
      pkgver: "1.2.3-1",
      arch: "x86_64",
    });
  });

  test("parsePkgInfo reads fields, accumulates depends, ignores comments/unknowns", () => {
    const info = parsePkgInfo(
      [
        "# Generated by makepkg",
        "pkgname = foo",
        "pkgver = 1.2.3-1",
        "pkgdesc = A demo package",
        "arch = x86_64",
        "url = https://example.test",
        "depend = bar",
        "depend = baz>=1.0",
        "",
        "size = 4096",
      ].join("\n"),
    );
    expect(info).toEqual({
      pkgname: "foo",
      pkgver: "1.2.3-1",
      arch: "x86_64",
      pkgdesc: "A demo package",
      depends: ["bar", "baz>=1.0"],
    });
  });
});
